apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-tom
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: tom
  template:
    metadata:
      labels:
        app: tom
    spec:
      containers:
      - name: tom
        image: vijay6594/project-k8s
        ports:
        - containerPort: 8080  # Port exposed by your application
