apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-ramya
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: ramya
  template:
    metadata:
      labels:
        app: ramya
    spec:
      containers:
      - name: ramya
        image: vijay6594/ramya:3
        ports:
        - containerPort: 8080  # Port exposed by your application
